Nested forms and polymorphic associations
SlevinKelevra/StackOverflow pull request #8
Opened 2017-06-20 11:04 UTC by SlevinKelevra

2017-06-20 11:43 UTC, vkurennov requested changes

2017-06-20 11:43 UTC, vkurennov commented on app/models/answer.rb
> +  accepts_nested_attributes_for :attachments
Добавь опцию `reject_if: :all_blank`, чтобы не было ошибок, если добавляем с пустыми файлами ответ

2017-06-20 11:43 UTC, vkurennov commented on app/models/question.rb
> +  accepts_nested_attributes_for :attachments
Добавь опцию `reject_if: :all_blank`, чтобы не было ошибок, если добавляем с пустыми файлами вопрос

2017-06-20 11:43 UTC, vkurennov commented on public/uploads/attachment/file/1/spec_helper.rb
> +# This file was generated by the `rails generate rspec:install` command. Conventionally, all
Папку public/uploads удали из репозитория и добавь в .gitignore, не стоит хранить добавляемые файлы в репозитории - это мусор.

2017-06-20 11:43 UTC, vkurennov commented on spec/acceptance/delete_files_to_question_spec.rb
> +  scenario 'Author deletes file', js: true do
А сценарий для не-автора?

2017-06-21 07:32 UTC, iBublik commented on spec/acceptance/delete_files_to_answer_spec.rb
> +  scenario 'Non - Author deletes file', js: true do
Сценарии должны описывать реальные user story. Разве не автор может удалять файлы? Правильнее было бы описать `Non authro is not able to delete files`

2017-06-21 07:32 UTC, iBublik commented on spec/controllers/attachments_controller_spec.rb
> +      question_user.attachments.create(file: file)
Это лучше было не в before блоке описывать, а в `let` блоке или даже в самом тесте. Потому что в каждом тесте нам нужен 1 файл, а создается 4 - чем больше тестов, тем больше времени они будут занимать, а запись в базу (особенно с файлами, там же еще на диск сохранение идет) дорогая операция

2017-06-21 07:32 UTC, iBublik commented on spec/controllers/attachments_controller_spec.rb
> +      it 'deletes attachment from question' do
И тут тоже - фактического не происходит, но в заголовке тесте почему указано, что "Не автор удаляет файл".

2017-06-26 06:46 UTC, merged